### ISSUE TITLE
Style tags aren't escaped

### ISSUE THREAD

**Issue by JangoSteve** [HashNuke/mogo-chat#2]
When posting a comment, `<style>` tags don't get escaped. Try typing something like:

```
<style>* { color: green; }</style>
```

And all the text turns green (note that copy/pasting the above code doesn't work, as pasted code turns into code blocks).

**Comment by jomo** [comment]
all html tags are not escaped at all.
`<a onclick="something_evil()">http://example.com</a>`

the demo is horribly breaking because of this..

**Comment by hugo** [comment]
It parses (what it thinks are) URLS and turns them into `<a>` tags, but you can bypass the filtering and embed images by using protocol relative urls e.g.

``` html
    <img src="//domain.tld/image.jpg"></img>
```

This also works for `<iframe>`s (you can embed a YouTube video, for example) etc.

Edit:

Oh also, in addition to `<style>` tags not being escaped, style attributes on elements are also allowed. e.g.

``` html
    <p style="font-size:200px;color:red;">
```

**Comment by chrismccord** [comment]
@HashNuke Take a look at how eric is escaping eex in hex_web, https://github.com/ericmj/hex_web/blob/master/lib/hex_web/web/html_engine.ex

**Comment by HashNuke** [comment]
@chrismccord Thanks for pointing to that link.
@JangoSteve Thank you for looking into the issue and reporting it - both here and on HN.

This should be fixed now.

EDIT: Leaving this open for a while just in case.

**Comment by HashNuke** [comment]
Don't seem to be a problem anymore. Closing this. Thanks @JangoSteve, @chrismccord and @JonApps for helping out
