### ISSUE TITLE
Credentials: Heroku

### ISSUE THREAD

**Issue by benbull** [HashNuke/mogo-chat#4]
Just followed the instructions to spin up a Mogo-Chat on Heroku but when I enter the credentials suggested I get;

"Maybe you don't have an account?"

**Comment by benbull** [comment]
I'm an idiot, ignore me - just read the f***ing instructions and did it again.

Sorry :+1:

**Comment by HashNuke** [comment]
@benbull totally fine Ben. You don't have to beat yourself up over filing an issue. Glad it worked now for you. Do report back if you find any issues.
